### ISSUE TITLE
wireguard install

### ISSUE THREAD

**Issue by Kirk-Div** [crozuk/pi-hole-wireguard-privoxy#1]
you're missing a couple of lines in your guide to install wireguard.

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7638D0442B90D010
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC

**Comment by crozuk** [comment]
Cheers - will get these added in when I get a sec.

**Comment by crozuk** [comment]
Updated
